dist: trusty
language: php
php:
- 7.2
- 7.3
sudo: false
env:
  global:
  - WP_VERSION=latest WP_MULTISITE=0
before_script:
- bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
- composer install
script:
- composer test
